@php($history = $consultation->patient->consultationHistory)
<style>
body{font-family:DejaVu Sans,sans-serif;color:#213140;font-size:13px}.sheet{max-width:960px;margin:0 auto}.head{display:flex;justify-content:space-between;gap:20px;padding-bottom:12px;border-bottom:2px solid #2f7aa9;margin-bottom:16px}.title{font-size:24px;font-weight:700;color:#2f7aa9}.muted{font-size:12px;color:#6d7f90}.section{border:1px solid #dce5ee;border-radius:10px;padding:14px;margin-bottom:14px}.section h3{margin:0 0 10px;font-size:16px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.row{padding:8px 0;border-bottom:1px solid #edf2f6}.row:last-child{border-bottom:none}.label{font-size:11px;text-transform:uppercase;color:#7c8f9f;font-weight:700}.pill{display:inline-block;background:#e8f2fa;color:#2f7aa9;border-radius:999px;padding:5px 10px;margin:4px 6px 0 0}
</style>
<div class="sheet">
<div class="head"><div><div class="title">Edge Clinic Consultation</div><div class="muted">Current Visit Summary</div></div><div style="text-align:right"><div><strong>{{ $consultation->patient->name }}</strong></div><div class="muted">{{ $consultation->patient->gender }} / {{ $consultation->patient->age }} yrs</div><div class="muted">Doctor: {{ $consultation->doctor?->name ?? 'Not assigned' }}</div></div></div>
<div class="section"><h3>Visit Details</h3><div class="grid"><div><div class="label">Date</div><div>{{ optional($consultation->visit_date)->format('d M Y') }}</div></div><div><div class="label">Time</div><div>{{ $consultation->visit_time ?: '-' }}</div></div><div><div class="label">Token</div><div>{{ $consultation->token_number ?: '-' }}</div></div><div><div class="label">Status</div><div>{{ ucfirst($consultation->status) }}</div></div></div></div>
<div class="section"><h3>Vitals</h3><div class="grid"><div><div class="label">BP</div><div>{{ ($consultation->bp_systolic ?: '-') . ' / ' . ($consultation->bp_diastolic ?: '-') }}</div></div><div><div class="label">Heart Rate</div><div>{{ $consultation->heart_rate ?: '-' }}</div></div><div><div class="label">SpO2</div><div>{{ $consultation->spo2 ?: '-' }}</div></div><div><div class="label">Temperature</div><div>{{ $consultation->temperature ?: '-' }}</div></div><div><div class="label">Weight</div><div>{{ $consultation->weight ?: '-' }}</div></div><div><div class="label">Height</div><div>{{ $consultation->height ?: '-' }}</div></div><div><div class="label">BMI</div><div>{{ $consultation->bmi ?: '-' }}</div></div><div><div class="label">GRBS</div><div>{{ $consultation->grbs ?: '-' }}</div></div></div></div>
<div class="section"><h3>Complaints And Examination</h3><div class="row"><div class="label">Chief Complaints</div><div>@forelse($consultation->chief_complaints ?? [] as $item)<span class="pill">{{ $item }}</span>@empty - @endforelse</div></div><div class="row"><div class="label">History Of Present Illness</div><div>{{ $consultation->history_of_present_illness ?: '-' }}</div></div><div class="row"><div class="label">Examinations</div><div>@forelse($consultation->examinations as $exam)<div>{{ $exam->system_name }}: {{ ucfirst($exam->finding_status) }}@if($exam->notes), {{ $exam->notes }}@endif</div>@empty - @endforelse</div></div></div>
<div class="section"><h3>Diagnosis And Plan</h3><div class="row"><div class="label">Diagnosis</div><div>@forelse($consultation->diagnoses as $diagnosis)<div>{{ $diagnosis->diagnosis_name }} @if($diagnosis->icd10_code) ({{ $diagnosis->icd10_code }}) @endif - {{ ucfirst($diagnosis->diagnosis_type) }}, {{ ucfirst($diagnosis->clinical_status) }}</div>@empty - @endforelse</div></div><div class="row"><div class="label">Investigations</div><div>@forelse($consultation->investigations as $investigation)<span class="pill">{{ $investigation->test_name }}</span>@empty - @endforelse</div></div><div class="row"><div class="label">Advice</div><div>{{ $consultation->advice ?: '-' }}</div></div><div class="row"><div class="label">Follow Up</div><div>{{ $consultation->follow_up_label ?: '-' }} @if($consultation->follow_up_date) on {{ $consultation->follow_up_date->format('d M Y') }} @endif</div></div></div>
<div class="section"><h3>Prescription</h3>@forelse($consultation->prescriptions as $prescription)<div class="row"><div class="label">{{ $prescription->medicine_name }}</div><div>{{ $prescription->pack ?: '-' }} | {{ $prescription->frequency ?: '-' }} | {{ $prescription->duration ?: '-' }} | {{ $prescription->instruction ?: '-' }}@if($prescription->details)<div>{{ $prescription->details }}</div>@endif</div></div>@empty<div>No medicines prescribed.</div>@endforelse</div>
<div class="section"><h3>History Snapshot</h3><div class="row"><div class="label">Past Medical History</div><div>{{ collect($history?->past_medical_history ?? [])->implode(', ') ?: '-' }}</div></div><div class="row"><div class="label">Drug Allergies</div><div>{{ collect($history?->drug_allergies ?? [])->implode(', ') ?: '-' }}</div></div><div class="row"><div class="label">Chronic Conditions</div><div>{{ collect($history?->chronic_conditions ?? [])->implode(', ') ?: '-' }}</div></div><div class="row"><div class="label">Ongoing Medications</div><div>{{ collect($history?->ongoing_medications ?? [])->implode(', ') ?: '-' }}</div></div></div>
</div>
